version: "2"

setup:
  concurrency: 4
  timeout: 5m
  tests: false
  go: '1.23'
  build-tags:
    - mytag
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

formatters:
  enable:
    - gofmt
    - goimports
    - gci
    - golines
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes: github.com/crypto-bundle/bc-wallet-common-lib-jwt
      format-only: true
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        #      - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/crypto-bundle/) # Custom section: groups all imports with the specified Prefix.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      skip-generated: true
      custom-order: true

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^* "
  exit-code: 2

linters:
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          db: snake
        use-field-name: true

    wsl:
      force-short-decl-cuddling: false
      force-err-cuddling: true

    govet:
      enable-all: true
      disable:
        - slog

    wrapcheck:
      ignore-sigs:
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        # bc-wallet-common-lib-errors
        - .ErrorWithCode
        - .ErrWithCode
        - .ErrorGetCode
        - .ErrGetCode
        - .ErrorNoWrap
        - .ErrNoWrap
        - .Errorf(
        - .ErrorOnly(
        - .Error(
        - .NewError(
        - .NewErrorf(

    exhaustive:
      check: [ ]
      explicit-exhaustive-switch: true
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/crypto-bundle/
            - github.com/mailru/easyjson
            - github.com/golang-jwt/jwt/v4

    revive:
      rules:
        - name: unexported-return
          severity: warning
          disabled: true

    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-names:
        - err
        - wg
        - ctx
      ignore-decls:
        - i int

    goheader:
      values:
        const:
          COMPANY: MY COMPANY
        regexp:
          AUTHOR: Aleksei Kotelnikov(gudron2s@gmail.com)
      template-path: ./copyright.tpl

  disable:
    - exhaustruct
  enable:
    - depguard
    - tagliatelle # couldn't set up complains about snake_case
    - wrapcheck # we need to set it up, swears at all our custom mistakes
    - revive # requires unnecessary comments on public variables and methods.
    - dupl #
    - funlen
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wsl
    - zerologlint
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  fast: true