// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package jwt

import (
	json "encoding/json"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(in *jlexer.Lexer, out *tokenClaim) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "uuid_map":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.UUIDMap = make(map[string]uuid.UUID)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 uuid.UUID
					if data := in.UnsafeBytes(); in.Ok() {
						in.AddError((v1).UnmarshalText(data))
					}
					(out.UUIDMap)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(out *jwriter.Writer, in tokenClaim) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid_map\":"
		out.RawString(prefix[1:])
		if in.UUIDMap == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.UUIDMap {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.RawText((v2Value).MarshalText())
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v tokenClaim) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v tokenClaim) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *tokenClaim) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *tokenClaim) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(l, v)
}
