// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package jwt

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC9cdda9cDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(in *jlexer.Lexer, out *stringArray) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(stringArray, 0, 4)
			} else {
				*out = stringArray{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 string
			v1 = string(in.String())
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC9cdda9cEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(out *jwriter.Writer, in stringArray) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			out.String(string(v3))
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v stringArray) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC9cdda9cEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v stringArray) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC9cdda9cEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *stringArray) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC9cdda9cDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *stringArray) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC9cdda9cDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt(l, v)
}
func easyjsonC9cdda9cDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt1(in *jlexer.Lexer, out *Field) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "key":
			out.Key = string(in.String())
		case "type":
			out.Type = FieldType(in.Uint8())
		case "integer":
			out.Integer = int64(in.Int64())
		case "string":
			out.String = string(in.String())
		case "interface":
			if m, ok := out.Interface.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Interface.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Interface = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC9cdda9cEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt1(out *jwriter.Writer, in Field) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.Type))
	}
	{
		const prefix string = ",\"integer\":"
		out.RawString(prefix)
		out.Int64(int64(in.Integer))
	}
	{
		const prefix string = ",\"string\":"
		out.RawString(prefix)
		out.String(string(in.String))
	}
	if in.Interface != nil {
		const prefix string = ",\"interface\":"
		out.RawString(prefix)
		if m, ok := in.Interface.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Interface.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Interface))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Field) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC9cdda9cEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Field) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC9cdda9cEncodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Field) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC9cdda9cDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Field) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC9cdda9cDecodeGithubComCryptoBundleBcWalletCommonLibJwtPkgJwt1(l, v)
}
